# Generated by Django 4.2.6 on 2023-10-06 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tarefas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsavel_tarefa',
            name='apelido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
